batch_size: 256
data_path: ./data/data/
dataset: dj30
encoder_path: ./result/SARL/encoder
generate_config: true
hidden_size: 256
input_config: false
input_config_path: config/input_config/data/custom.yml
input_encoder_config: false
input_encoder_config_dict: config/input_config/agent/SARL/encoder.yml
lr: 0.01
num_day: 10
num_epoch: 10
num_layer: 1
optimizer: Adam
output_config_path: config/output_config/data
seed: 12345
split_proportion:
- 0.8
- 0.1
- 0.1
technical_indicator:
- high
- low
- open
- close
- adjcp
- zopen
- zhigh
- zlow
- zadjcp
- zclose
- zd_5
- zd_10
- zd_15
- zd_20
- zd_25
- zd_30
