
#type: args

train:
  epochs: 200
  batch_size: 16 
  lr: 1.0e-3

diffusion:
  layers: 4 
  channels: 64 
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"

model:
  is_unconditional: 0
  timeemb: 128
  featureemb: 16
  target_strategy: "random"
