df_dict: data/data/dj30/test.csv
initial_amount: 10000
net_path: result/PM/SARL/encoder/best_model/LSTM.pth
num_day: 5
tech_indicator_list:
- high
- low
- open
- close
- adjcp
- zopen
- zhigh
- zlow
- zadjcp
- zclose
- zd_5
- zd_10
- zd_15
- zd_20
- zd_25
- zd_30
transaction_cost_pct: 0.001
