batch_size: 256
data_path: ./data/data/
dataset: dj30
discriptor_path: ./result/invest_imitator/logic_discriptor
generate_config: true
hidden_size: 256
input_config: false
input_config_path: config/input_config/data/custom.yml
num_day: 10
num_epoch: 10
optimizer: Adam
output_config_path: config/output_config/data
rank_name_list:
- AR
- SR
- MDD
- ER
- WR
seed: 12345
split_proportion:
- 0.8
- 0.1
- 0.1
