df_path: data/train.csv
initial_amount: 100000
length_day: 1
tech_indicator_list:
- feature_0
- feature_1
- feature_2
- feature_3
- feature_4
- feature_5
- feature_6
- feature_7
- feature_8
- feature_9
- feature_10
transaction_cost_pct: 0.0