df_path: data/data/dj30/train.csv
initial_amount: 100000
length_day: 10
tech_indicator_list:
- zopen
- zhigh
- zlow
- zadjcp
- zclose
- zd_5
- zd_10
- zd_15
- zd_20
- zd_25
- zd_30
transaction_cost_pct: 0.001